import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'appsknowledgeBase.manageArticles',
        path: `/manage-articles`,
        title: 'Manage Articles',
        translateKey: 'nav.appsknowledgeBase.manageArticles',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'enrolledCourses',
        path: `/enrolled-courses`,
        title: 'Enrolled Courses',
        translateKey: 'nav.entrolledCourses',
        icon: 'enrolledCourse',
        type: NAV_ITEM_TYPE_ITEM,
        // authority: ['student'],
        authority: [],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'userAdmin',
        path: '/userAdmin',
        title: 'Users',
        translateKey: 'nav.singleMenuItemc',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'invoicelist',
        path: '/invoice-list',
        title: 'Invoices',
        translateKey: 'nav.singleMenuItemc',
        icon: 'invoiceSingleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'groupMenu',
        path: '',
        title: 'Content',
        translateKey: 'nav.groupMenu.groupMenu',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'groupMasdenu.collapse',
                path: '',
                title: 'Create Course',
                translateKey: 'nav.groupMenu.collapse.cfollapse',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.casdollapse.item1',
                        path: '/add-course',
                        title: 'Add Course',
                        translateKey: 'nav.grouasdpMenu.collapse.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [
                            'Instructor',
                            'Organization',
                            'admin',
                            'super admin',
                            'manager',
                            'company',
                        ],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.collaasdpse.item2',
                        path: '/course-list',
                        title: 'Course List',
                        translateKey: 'nav.groupMdasenu.collapse.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            // {
            //     key: 'groupMasdenu.collapse.adminItem',
            //     path: 's-admin',
            //     title: 'Admin',
            //     translateKey: 'nav.groupMenu.collapse.cfollapse',
            //     icon: 'adminGroupMenu',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [],
            //     // 'superAdmin'
            //     subMenu: [
            //         {
            //             key: 'groupMenu.casdollapse.AdminItem',
            //             path: 's-admin/admin',
            //             title: 'View All Admin',
            //             translateKey: 'nav.grouasdpMenu.collapse.AdminItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'groupMenu.collaasdpse.AdminItem',
            //             path: 's-admin/create-admin',
            //             title: 'Create New Admin',
            //             translateKey: 'nav.groupMdasenu.collapse.AdminItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'groupMasdenu.collapse.ManagerItem',
            //     path: '',
            //     title: 'Manager',
            //     translateKey: 'nav.groupMenu.collapse.cfollapse',
            //     icon: 'managerGroupMenu',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [],
            //     // '','Instructor', 'Organization'
            //     subMenu: [
            //         {
            //             key: 'groupMenu.casdollapse.ManagerItem',
            //             path: '/manager',
            //             title: 'View All Manager',
            //             translateKey: 'nav.grouasdpMenu.collapse.ManagerItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'groupMenu.collaasdpse.ManagerItem',
            //             path: '/create-manager',
            //             title: 'Create New Manager',
            //             translateKey: 'nav.groupMdasenu.collapse.ManagerItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'groupMasdenu.collapse.EditorItem',
            //     path: '',
            //     title: 'Editor',
            //     translateKey: 'nav.groupMenu.collapse.cfollapse',
            //     icon: 'editorGroupMenu',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [],
            //     // '','Instructor', 'Organization'
            //     subMenu: [
            //         {
            //             key: 'groupMenu.casdollapse.EditorItem',
            //             path: '/editors',
            //             title: 'View All Editors',
            //             translateKey: 'nav.grouasdpMenu.collapse.EditorItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'groupMenu.collaasdpse.EditorItem',
            //             path: '/create-editor',
            //             title: 'Create New Editor',
            //             translateKey: 'nav.groupMdasenu.collapse.EditorItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'groupMasdenu.collapse.InstructorItem',
            //     path: '',
            //     title: 'Instructor',
            //     translateKey: 'nav.groupMenu.collapse.cfollapse',
            //     icon: 'instructorGroupMenu',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [],
            //     // '','Instructor', 'Organization'
            //     subMenu: [
            //         {
            //             key: 'groupMenu.casdollapse.InstructorItem',
            //             path: '/instructor',
            //             title: 'View All Instructor',
            //             translateKey:
            //                 'nav.grouasdpMenu.collapse.InstructorItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'groupMenu.collaasdpse.InstructorItem',
            //             path: '/create-instructor',
            //             title: 'Create New Instructor',
            //             translateKey:
            //                 'nav.groupMdasenu.collapse.InstructorItem',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [],
            //             subMenu: [],
            //         },
            //     ],
            // },
            {
                key: 'groupMasdenu.collapse.NuserItem',
                path: '',
                title: 'User',
                translateKey: 'nav.groupMenu.collapse.cfollapse',
                icon: 'userGroupMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                // '','Instructor', 'Organization'
                subMenu: [
                    {
                        key: 'groupMenu.collaasdpse.NUserItem',
                        path: '/create-user',
                        title: 'Create New User',
                        translateKey: 'nav.groupMdasenu.collapse.NUserItem',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.casdollapse.InstructorItem',
                        path: '/users',
                        title: 'View All User',
                        translateKey:
                            'nav.grouasdpMenu.collapse.InstructorItem',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'groupMasdenu.collapse.ApprovalsItem',
                path: '',
                title: 'Approvals',
                translateKey: 'nav.groupMenu.collapse.cfollapse',
                icon: 'approvalMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.casdollapse.profilepiclist',
                        path: '/profile-picture/list',
                        title: 'Profile Picture',
                        translateKey: 'nav.grouasdpMenu.collapse.profilepiclist',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'groupMeadnu.single',
                path: '/group-singleasd-menu-item-view',
                title: 'Plan',
                translateKey: 'nav.grasdoupMenu.single',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'singledMensdfuItem',
                path: '/single-menu-view',
                title: 'Admin',
                translateKey: 'nav.sinsdfgleMenuItemc',
                icon: 'singleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'singledMdenuItem',
                path: '/single-menu-view',
                title: 'Staff',
                translateKey: 'nav.singleMenuItemc',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'singleddfMenuItem',
                path: '/single-menu-view',
                title: 'Reports',
                translateKey: 'nav.singleMenuItemc',
                icon: 'collapseMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'singleddfntem',
                path: '/updateUser',
                title: 'Profile',
                translateKey: 'nav.singleMenuItemc',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'singleddfnuItem',
                path: '/single-menu-view',
                title: 'Setting',
                translateKey: 'nav.singleMenuItemc',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
